### PR TITLE
Move middleware into better structure. Fix imports. Comments etc.

### PR DESCRIPTION
**Pull request by jbrooksuk**
- Move into `Http/Middleware` to mimic the Laravel setup.
- Added comments.
- Always fully import the facades. If you remove them from the `app.aliases` array, your package won't work anymore.
- Use four spaces, if you want to follow PSR.
- Don't use `header` and `App`. We can use Symfony for this.
- Remove unused imports.

### CODE REVIEW

**Comment by Jord-JD** [comment]
Thanks!

Would you mind changing point 3 of the readme to reflect the new namespace?

**Comment by jbrooksuk** [comment]
Sure!

**Comment by jbrooksuk** [comment]
Done!

**Comment by jbrooksuk** [comment]
Rebased!

**Comment by Jord-JD** [comment]
Merged! Thanks for the contribution.

**Pull request merged**
