### PR TITLE
Make sure we're installing illuminate contracts and support

### PR DESCRIPTION
**Pull request by jbrooksuk**
Also, is `5.2.1` really the minimum version you're aiming for? `5.5.9` would be better as it's the minimum supported version by PHP.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
This also:
1. Makes the package 5.1 and 5.2 compatible.
2. Added `.gitattributes` and `.gitignore`.

**Comment by Jord-JD** [comment]
Looks good. I'm curious why you removed the `type` attribute from `composer.json`?

**Comment by jbrooksuk** [comment]
> The type of the package. It defaults to library.

https://getcomposer.org/doc/04-schema.md#type

**Comment by Jord-JD** [comment]
Never realised this. Thanks for the insight.

Good catch on the PHP version. The `composer.json` was taken from an old project and modified.

Would you mind bumping up the version as you suggested, and I'll get this merged?

**Comment by jbrooksuk** [comment]
Done!

**Comment by Jord-JD** [comment]
Thanks James!

**Pull request merged**
